### ISSUE TITLE
Leaking file descriptors

### ISSUE THREAD

**Issue by bradshjg** [bradshjg/desktop#14]
This manifested as an inability to launch a Rails environment due to too many open file desciptors when using an SSH-based virtual repo.

Cursory investigation showed a lot of `inotifywait` processes running...not sure where they came from but `pkill -f inotifywait` was able to make the environment usable again.

It's not clear to me whether we're launching processes that never exit or if there's something else afoot...but it's painful 😄

It's maybe a bit weird that we have 1,000s of SSH connections coming in and need to ensure that all of them are cleaned up.

**Comment by bradshjg** [comment]
Looks like this is specific to this codespace, there's a custom `~/.ssh/rc` that is currently spawning `inotifywait` for every connection 😅. They are backgrounded and never get reaped

```
@bradshjg ➜ ~/.ssh $ cat ~/.ssh/rc 
# Sets up a process to keep the codespace alive while editing files over ssh
inotifywait --monitor --format '%T' --timefmt '%s' /workspaces/repo 2> /dev/null > /workspaces/.codespaces/shared/active-clients-monitor.json &

...
```

We'll want to fix that to ensure that it's only launched if a process doesn't already exist.

**Comment by cheshire137** [comment]
Another temporary workaround to make it not fill up so fast:

```sh
sudo sh -c "echo 8192 > /proc/sys/fs/inotify/max_user_instances"
```

**Comment by bradshjg** [comment]
Fixed in the Codespace's `~/.ssh/rc`
