### ISSUE TITLE
Diff for new files doesn't work

### ISSUE THREAD

**Issue by cheshire137** [bradshjg/desktop#3]
Hey Jimmy! This fork has been working very well for me for the last couple of weeks while I use Codespaces, alongside your [virtual repo server extension](https://github.com/bradshjg/gh-desktop-virtual-repo-server-extension). Thank you!

I've noticed that if I introduce a new file in a virtual repository, the diff doesn't display in Desktop. Instead it just shows a spinner in the main panel:

![image](https://user-images.githubusercontent.com/82317/143142732-60bc0682-0869-4743-b001-c9a614dc14b7.png)

I see the following in the inspector:

```javascript
Uncaught (in promise) ExecFileError: {"killed":false,"code":1,"signal":null,"cmd":"git diff --no-ext-diff --patch-with-raw -z --no-color --no-index -- /dev/null sample-new-file.txt"}
    at file:///Applications/GitHub%20Desktop%20(Experimental).app/Contents/Resources/app/renderer.js:55:143228
mn @ client.ts:8
(anonymous) @ client.ts:24
Promise.then (async)
(anonymous) @ spawn.ts:38
nr @ spawn.ts:37
Br @ diff.ts:186
updateChangesWorkingDirectoryDiff @ app-store.ts:2392
_loadStatus @ app-store.ts:2011
```

**Comment by bradshjg** [comment]
With the release of

* https://github.com/bradshjg/desktop/releases/tag/release-3.1.2-beta1-virtual

As far as I can tell this is fixed, I'm guessing it was somehow related to the specific git interface that was trying to get this data...and now that's all dugite's business 😄

**Comment by cheshire137** [comment]
Yep, I see the lines in the new file now instead of a spinner, thank you!
